### ISSUE TITLE
Wrong scale on Steam Deck

### ISSUE THREAD

**Issue by alvarosg** [Tarnadas/smmdb-client#16]
Hi!

The precompiled linux tool opens on the Steam Deck, but the scale is totally off with no apparent easy way to reduce the window size (e.g. even if I try, this seems to be the minimum window size the app wants), and does not let me reduce it from th edges of the window.
![PXL_20221205_132003888](https://user-images.githubusercontent.com/12649253/205647815-56a278c4-cb67-4a0c-8e3b-6ebc13e0e649.jpg)

Otherwise, with some scrolling and shifting wizardy I was able to check that the tool itsels works, it is just that it is practically impossible to use it to select a desired level (I just managed to use it to add some levels at random).

Thanks!

**Comment by alvarosg** [comment]
I have seen some more evidence that suggest that this is probably some bug with Steam OS itself, because:

(1) The screenshot I showed before was for the default "Global scale" factor of 100%.
(2) If I increase the factor to 106.25% (The next allowed). Other apps slighly increase in size but this one actually decreases in size and becomes usable.
(3) If I keep increasing the factor beyond 106.25, then this app also keeps increasing in size as expected.

So there is just something weird with the behavior at 100% "Global scale".

**Comment by Tarnadas** [comment]
Hey,
please see this issue:
https://github.com/rust-windowing/winit/issues/2401

Try starting the software with the environment variable `WINIT_X11_SCALE_FACTOR=1` being set.
Someone on Discord also had the problem on Steam Deck and this fixed it.
